# Generated by Django 5.1 on 2024-11-03 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RegLogCreate', '0008_remove_user_iseventorganizer_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAccepted', models.BooleanField(default=False)),
                ('appealedBy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appealedBy', to='RegLogCreate.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegLogCreate.user')),
            ],
        ),
    ]
