# Generated by Django 5.1 on 2024-11-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizerAppeal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizerappeal',
            name='appealedBy',
        ),
        migrations.AddField(
            model_name='organizerappeal',
            name='acceptedBy',
            field=models.IntegerField(default=-1),
        ),
    ]
