# Generated by Django 5.1 on 2024-11-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizerAppeal', '0002_remove_organizerappeal_appealedby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizerappeal',
            name='id',
        ),
        migrations.AddField(
            model_name='organizerappeal',
            name='appealID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
