# Generated by Django 5.1.1 on 2024-10-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_userprofile_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_img_data',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_img_data',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
