# Generated by Django 5.1.1 on 2024-10-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_userprofile_cover_img_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_img_data',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_img_data',
        ),
    ]
