# Generated by Django 5.1.1 on 2024-11-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_alter_userprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(default='cover_images/default.jpg', upload_to='cover_images/'),
        ),
    ]
