# Generated by Django 5.1.1 on 2024-11-28 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_alter_userprofile_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
