# Generated by Django 5.1.2 on 2024-10-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventRegistration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='inclusions',
        ),
    ]
