# Generated by Django 5.1.2 on 2024-10-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRegistration', '0002_remove_registration_inclusions'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='contactnum',
            field=models.CharField(default='000', max_length=15),
        ),
        migrations.AddField(
            model_name='registration',
            name='emergencynum',
            field=models.CharField(default='000', max_length=15),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(default='M', max_length=100),
        ),
    ]
