# Generated by Django 5.1.2 on 2024-10-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRegistration', '0003_registration_contactnum_registration_emergencynum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='age_category',
            field=models.CharField(choices=[('20 and below', '20 and below'), ('21 to 30', '21 to 30'), ('31 to 40', '31 to 40'), ('41 to 50', '41 to 50'), ('51 and above', '51 and above')], default='20 and below', max_length=30),
        ),
    ]
