# Generated by Django 5.1.2 on 2024-11-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRegistration', '0006_registration_inclusions'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='category_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
