# Generated by Django 5.1 on 2024-11-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRegistration', '0007_registration_category_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.CharField(default='@gmail.com', max_length=20),
        ),
    ]
