# Generated by Django 5.1 on 2024-09-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventid', models.BigAutoField(primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=100)),
                ('eventdetails', models.TextField()),
                ('eventcategory', models.JSONField()),
                ('eventlocation', models.CharField(max_length=100)),
                ('eventdate', models.DateField()),
                ('eventtime', models.TimeField()),
                ('dateposted', models.DateTimeField(auto_now_add=True)),
                ('inclusions', models.JSONField()),
                ('bannerimage', models.ImageField(upload_to='')),
                ('inclusionimage', models.ImageField(upload_to='')),
                ('sizechartimage', models.ImageField(upload_to='')),
                ('racerouteimage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveSmallIntegerField()),
                ('isEventOrganizer', models.BooleanField(default=False)),
            ],
        ),
    ]
