# Generated by Django 5.1 on 2024-10-01 04:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegLogCreate', '0005_alter_event_bannerimage_alter_event_inclusionimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bannerimage',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/photos/eventbanner/'), upload_to=''),
        ),
    ]
