# Generated by Django 5.1 on 2024-11-05 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegLogCreate', '0008_remove_user_iseventorganizer_user_usertype'),
        ('RegLogCreate', '0011_user_groups_user_user_permissions'),
    ]

    operations = [
    ]
