# Generated by Django 5.1 on 2024-11-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegLogCreate', '0012_merge_20241105_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isEventOrganizer',
            field=models.BooleanField(default=False),
        ),
    ]
