# Generated by Django 5.1 on 2024-11-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegLogCreate', '0013_user_iseventorganizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizerId',
            field=models.IntegerField(default=0),
        ),
    ]
