# Generated by Django 5.1 on 2024-11-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegLogCreate', '0014_event_organizerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
