# Generated by Django 5.1.2 on 2024-11-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegLogCreate', '0017_event_isclosed_event_maxslots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventdate',
            field=models.DateTimeField(),
        ),
    ]
