# Generated by Django 5.1.2 on 2024-12-09 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegLogCreate', '0020_alter_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='closedate',
            field=models.DateField(default=datetime.date(2024, 12, 31)),
        ),
    ]
