# Generated by Django 5.1.2 on 2024-12-09 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegLogCreate', '0021_event_closedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='closedate',
            field=models.DateTimeField(default=datetime.date(2024, 12, 31)),
        ),
    ]
