# Generated by Django 5.1.1 on 2024-10-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='cover_images/'),
        ),
    ]
