# Generated by Django 5.1.1 on 2024-11-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizerEventPage', '0002_event_cover_photo_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50),
        ),
    ]
