# Generated by Django 5.1.1 on 2024-11-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizerEventPage', '0003_alter_participant_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Cancelled', 'Cancelled')], max_length=50),
        ),
    ]
